Footer
Interdisciplinary-Project/Frontend pull request #11
Opened 2024-08-31 00:08 UTC by SayRyan

Matheus, fiz o footer aqui, mano. Verifica aí, fazendo favor.
@MatGPereira

2024-08-31 15:53 UTC, MatGPereira requested changes

2024-08-31 15:53 UTC, MatGPereira commented on src/components/footer/index.jsx
> +import tailwindConfig from "../../../tailwind.config";
Não é necessário realizar esta importação para que aquelas configurações de cores do tailwind funcionem, é bom exluir.

2024-08-31 15:53 UTC, MatGPereira commented on src/components/footer/index.jsx
> +        <footer className="w-full h-[234px] bg-light-social-brand absolute bottom-0">
Não deixe o <footer></footer>` como `absolute`, porque esse não é o melhor jeito de mantê-lo sempre embaixo no nosso contexto. Pode deixar ele sem nada mesmo. Quando precisarmos ajustá-lo (se é que vamos mesmo precisar), nós iremos mexer em outro lugar.

Digo isso por 2 motivos:
1. Nenhuma de nossas telas que possuem um `<footer></footer>` são pequenas o suficiente para que ele não fique sempre embaixo. E no caso mobile nós iremos aplicar outras coisas do tailwind para que ele precise ficar como um menu inferior nos casos mobile.
2. Caso venhamos a precisar mesmo estilizar a página, porque o `<footer></footer>` não ficou como queŕiamos, iremos utilizat algumas propriedades de flex containers para que o conteúdo principal da página (a nossa `<main></main>`) ocupe todo o espaço possível, obrigando o `<footer></footer>` a ficar embaixo.

2024-08-31 15:53 UTC, MatGPereira commented on src/components/footer/index.jsx
> +                className="flex gap-12 items-center cursor-pointer px-[188px] pt-[70px]"
Imagino que você tenha visto que podemos configurar as cores para que não precisemos o tempo todo escrever `text-[#FAFAFA]`, por exemplo. 

Existe uma extensão do tailwind que você deve baixar. Assim, ele irá sempre mostrar para você as opções de classes enquanto estiver escrevendo. Ou seja, ao invés de usar, por exemplo, `px-[188px]`, é mais aconselhável nós utilizarmos `px-48`, que equivale a `px-[192px]`. 
Apesar da diferença de valor, é uma diferença muito pequena e que não ir afetar visualmente o nosso layout comparado ao figma. Assim, instale a extensão e altere os lugares para remover todos esses `[px]` dos estilos. Esse recurso é necessário somente em alguns casos.

Segue a imagem da extensão:
![image](https://github.com/user-attachments/assets/2256e81b-0757-4822-a32a-90a20f3869c7)

## Observação

Note que a cima eu falei sobre `px-48`. Caso queira, você consegue descobrir (sem a extensão e sem a documentação) que esse `48` significa `192px` simplesmente fazendo `49 * 4`. Isso vale para todas as medidas utilizadas no tailwind.

2024-08-31 15:53 UTC, MatGPereira commented on src/components/footer/index.jsx
> +                <small className="text-social-gray">© Todos direitos reservados</small>
Não é muito indicado você colocar diretamente esse tipo de caractere especial no HTML, porque ele pode não ser muito bem compreendido em outros editores que estiverem configurados com um charset diferente.

Assim, nesses casos, é mais aconselhável utilizar o código `&copy;`, que representa o símbolo do `copyright`.
Segue um link para um artigo curso que mostra sobre esses códigos: [https://www.devmedia.com.br/html-entities-html-symbols-html-characters/1011](devmedia)

## Observação

É útil salientar que isso não significa que você deve usar esses códigos para TODOS os símbolos. Use com moderação e da melhor forma possível, lembrando que a legibilidade do código é algo essencial.

2024-08-31 15:53 UTC, MatGPereira commented on src/components/footer/index.jsx
> +                    className="max-w-[580px] text-[16px]"
O que vou dizer é questão de padronização, não há um certo e um errado neste caso, então vou dizer o que é mais comum: eu nunca vi um código onde as tag's são quebradas desta forma com apenas uma propriedade dentro dela. Normalmente, ou se quebra as linhas quando há 2 ou mais propriedades ou quando a linha ultrapassa o comprimento de 80 caracteres. Daí, precisamos escolher um ou outro, não ambos.

Porém, como todos os outros componentes estão seguindo o padrão de quebra de linha quando há 2 ou mais propriedades, então se faz necessário arrumar aqui também para manter a correta padronização do código.

## Observação

Como programador, é essencial lembrar de algumas coisas: um bom programador não é aquele que somente escreve códigos assim como um bom redator não é aquele que somente escreve as palavras no papel. Para ser um bom redator se faz necessário seguir muitas regras e estruturar muito bem o texto que se está escrevendo.
O mesmo vale para um programador. Um bom código é aquele que, além de funcionar corretamente, é legível, segue o mesmo padrão em toda a sua extensão e é organizado.

2024-08-31 23:09 UTC, SayRyan commented on src/components/footer/index.jsx
> +                    className="max-w-[580px] text-[16px]"
Não entendi o que tem que ser feito aqui.
Eu preciso tirar o px do height, width e do font-size também?
@MatGPereira

2024-08-31 23:14 UTC, MatGPereira commented on src/components/footer/index.jsx
> +                    className="max-w-[580px] text-[16px]"
Não, no momento a tag `<p></p>` está assim no seu código:
```html
<p
  className="..."
></p>
```

O que eu comentei é que só se quebra linha nas tag's quando se tem mais de uma propriedade. Ou seja, se fosse algo assim:
```html
<p
  className="..."
  aria-label="..."
  title="..."
></p>
```

Quando se tem apenas um atributo ali na tag, então devemos deixar assim:
```html
<p className="..."></p>
```

2024-08-31 23:15 UTC, SayRyan commented on src/components/footer/index.jsx
> +                    className="max-w-[580px] text-[16px]"
Ah, saquei, mano KKKKKKKKKKKKKK

2024-08-31 23:16 UTC, SayRyan commented on src/components/footer/index.jsx
> +                    className="max-w-[580px] text-[16px]"
Eu preciso tirar o px do height, width e do font-size também?

@MatGPereira

2024-08-31 23:19 UTC, MatGPereira commented on src/components/footer/index.jsx
> +                    className="max-w-[580px] text-[16px]"
SIm, mas não sei se é da forma como está pensando. Mas eu não disse para fazer isso nesse comentário.
Eu disse no terceiro comentário. Dá uma olhadinha lá que acredito que vai estar bem explicado como fazer.

2024-08-31 23:29 UTC, SayRyan commented
@MatGPereira 

Fiz as alterações lá, mano. Na parte do max-w-[580px] eu mantive, pois o rem só estava indo na máxima de 96 e não estava quebrando do jeito que eu queria. Imagem eu mantive também, pois não vi nenhuma necessidade ter que substituir para rem também.

2024-08-31 23:35 UTC, MatGPereira requested changes

2024-08-31 23:35 UTC, MatGPereira commented on src/components/footer/index.jsx
> +        <footer className="w-full h-[234px] bg-light-social-brand">
Eu acho que esqueci de comentar antes, mas normalmente não precisamos controlar a altura do rodapé com um valor fixo. Somente de colocarmos os elementos internos dele da forma correta e ajustarmos os paddings, tudo fica bem. É o mais comum de se fazer.

Então, faça o teste, remova o `h-[234px]` e adicione os paddings correspondentes do figma e vai ver que tudo vai se manter como deve. Assim é mais fácil de se trabalhar e se evita um overflow do conteúdo.

2024-08-31 23:35 UTC, MatGPereira commented on src/components/footer/index.jsx
> +                    className="w-[95px] h-[95px]"
Sobre a imagem, vou te explicar o porquê de ser mais vantajoso se usar `rem`.

Quando você deixa assim em `px`, se o celular/desktop do usuário estiver com o tamanho da fonte aumentado a imagem não irá acompanhar essa alteração. Ela continuará fixa com `95px` e tudo vai ficar desproprocional. Porém, se você colocar em `rem`, a imagem irá se adaptar a essa configuração customizada do usuário e a proporção se manterá, assim como também a acessibilidade.

Porque se o usuário está aumentado a fonte, então ele quer que tudo fique grande, inclusive as imagens. Por isso que você deve colocar `rem` ao invés de se manter em `px`.

2024-09-01 00:09 UTC, SayRyan commented on src/components/footer/index.jsx
> +                    className="w-[95px] h-[95px]"
Fiz as alterações, mano.

@MatGPereira

2024-09-01 00:30 UTC, MatGPereira approved these changes

2024-09-01 00:30 UTC, merged