Os cards estão no caminho de ficar prontos, mas faltam alguns ajustes.
Interdisciplinary-Project/Frontend pull request #13
Opened 2024-09-01 05:17 UTC by SayRyan

@MatGPereira 

Mano, tava fazendo os cards, mas n tô conseguindo colocar a merda dos ícones por cima da imagem. Tentei diversos z-index, mas não está indo.

2024-09-01 20:44 UTC, MatGPereira commented on src/components/cards/index.jsx
> +                                <svg
Nós iremos usar uma biblioteca de ícones do react para não precisarmos utilizar diretamente os SVG's no nosso código. Porém, pode deixar assim por enquanto e depois nós arrumamos.

2024-09-03 21:47 UTC, SayRyan commented on src/components/cards/index.jsx
> +                                <svg
Mano, então, isso que eu iria te falar. Eu vou mudar e colocar aquela biblioteca do lucide-react msm.
O código ainda não está pronto, pois está faltando alguns ajustes. Irei deixar tudo certinho aq e te mandar.

2024-09-04 01:30 UTC, SayRyan commented on src/components/cards/index.jsx
> +                                <svg
@MatGPereira 

Fiz as alterações necessárias, mano. Agora só falta sua aprovação.

2024-09-04 13:12 UTC, MatGPereira requested changes

2024-09-04 13:12 UTC, MatGPereira commented on src/components/cards/index.jsx
> +          <div
Acredito que esta não seja a melhor forma de se fazer isso.

Me parece que está usando esta `<div></div>` para criar aquela animação de escurecer a imagem.
Ao invés disso, é mais simples deletar esta `<div></div>` e adicionar um `hover:brightness-50 transition duration-500 ease-in-out` diretamente na tag `>img />`. 

O efeito será o mesmo, mas iremos economizar código e o HTML ficará mais fácil e simples de ser lido.

2024-09-04 13:12 UTC, MatGPereira commented on src/components/cards/index.jsx
> +            alt="Imagem de uma pessoa"
Não se esqueca de que os atributos `alt` de imagens devem ser descritivos. Por exemplo, no caso da sua imagem, você deveria escrever algo assim: Pessoa sorrindo de pele morena, cabelos castanhos liso usando uma camisa de cor preta.

Isso sim é um `alt` acessível.

2024-09-04 13:12 UTC, MatGPereira commented on src/components/cards/index.jsx
> +              rel="noopener noreferrer"
Aqui, onde você escrever `rel="noopener noreferrer"` deveria ser `rel="noopener noreferrer external nofollow"`

2024-09-04 13:12 UTC, MatGPereira commented on src/components/cards/index.jsx
> +        <ul className="absolute flex gap-8 bottom-[10.125rem] z-[3]">
No caso do atributo `z-index`, não precisa escrever `z-[3]`. Pode usar os atributos nativos do tailwind, não vai ser um problema. Pode colocar um `z-10` que não vai ser um problema além de deixar mais claro o que está acontecendo.

2024-09-04 13:12 UTC, MatGPereira commented on src/components/cards/index.jsx
> +    <div className="relative w-[22rem] h-[28rem]">
# Alterações opcionais

Ao invés de estruturar seu card inteiro desta forma, o que te obriga muito a utilizar o `absolute` e o `relative`, você poderia fazer algo assim:

```html
<article className="bg-social-white w-[22rem] h-[28rem] shadow-default flex flex-col">
  <header className="overflow-hidden relative">
    <img 
      src="..."
      alt="..."
      className="hover:brightness-50 transition duration-500 ease-in-out" 
    />
    <ul className="absolute bottom-0">
      <li>
        <a></a>
      </li>
      <li>
        <a></a>
      </li>
    </ul>
  </header>
  <div className="py-2 px-4">
    <h2 className="mb-[0.5rem] font-bold">Richard Ryan</h2>
    <p className="opacity-90"></p>
  </div>
</article>
```

**O.B.S.:** Eu fiz essa estrutura e as estilizações diretamente aqui, então você provavelmente vai ter que corrigir algumas classes e coisas do tipo para fazer tudo ficar como deve ser. Mas essa estrutura é mais organizada, exige menos usos do `absolute` para deixar as coisas no lugar. Ou seja, vai ser mais responsivo.

2024-09-04 13:12 UTC, MatGPereira commented on src/components/cards/index.jsx
> +    <div className="relative w-[22rem] h-[28rem]">
Aqui você deve fazer uso da tag semântica `<article></article>`. Quando uma parte da UI é autocontida (ou seja, você sabe o que aquilo quer dizer sem precisar do resto da página para entender), como neste caso, a tag `<article></article>` é muito bem-vinda.

2024-09-04 23:34 UTC, merged