Criação da sidebar
Interdisciplinary-Project/Frontend pull request #20
Opened 2024-09-08 23:46 UTC by SayRyan

@MatGPereira 

Mano, avalia meu código da sidebar.

2024-09-09 04:12 UTC, MatGPereira requested changes

2024-09-09 04:12 UTC, MatGPereira commented on src/components/sidebar/index.jsx
> +  function Openbar() {
Esse código não está incorreto, mas não é assim que trabalhamos quando desenvolvemos com react.
Nós precisamos usar um hook específico chamado `useRef`. Somente em casos raros e muito específicos que usamos esse tipo de comando.

Podemos pegar essa semana para eu mostrar a forma correta de se fazer.

2024-09-09 04:12 UTC, MatGPereira commented on src/components/sidebar/index.jsx
> +    <div>
Para esse tipo de conteúdo existe uma tag semântica correta de ser usada. No lugar desta `<div></div>` você deve usar a tag `<aside></aside>`.

2024-09-09 04:12 UTC, MatGPereira commented on src/components/sidebar/index.jsx
> +        className="sidebar fixed top-0 bottom-0 right-0 p-2 w-44 overflow-y-auto
Porque você colocou o `overflow-y-auto`? Estava dando algum problema?

Além disso, você não deve colocar o tamanho da `SIdebar` fixo com o `w-44`. Neste caso, o ideal é você colocar uma largura em porcentagem (uns 80% ou 70%) da tela e estabelecer uma largura máxima para que não quebre em alguma outra possível situação.

Se não me engano, a classe `w-2/3` representa justamente essa largura de mais ou menos `80%`

2024-09-09 04:12 UTC, MatGPereira commented on src/components/sidebar/index.jsx
> +      <div className="fixed right-2 bottom-8">
O ideal é que o botão que abre a nossa `SIdebar` não fique dentro do componente. O melhor é que seja possível abrir ela a partir do clique em qualquer botão.
Ou seja, devemos poder dizer assim: `SIdebar`, quando eu clicar nesse cara você abre. Ou seja, devemos poder escolher quando ela vai abrir de forma flexível.

2024-09-09 04:12 UTC, MatGPereira commented on src/pages/public/home/index.jsx
> +    answer: 'Basta apenas realizar o cadastro e ir pessoalmente conhecer/conversar com os chefes do grupo.',
É interessante passar o endereço deles aqui. Desta forma, a sua resposta cria mais perguntas do que responde.

A final, onde eu realizo o cadastro e onde ficam os chefes?

2024-09-09 23:06 UTC, SayRyan commented on src/components/sidebar/index.jsx
> +  function Openbar() {
Blz

2024-09-09 23:12 UTC, SayRyan commented on src/components/sidebar/index.jsx
> +        className="sidebar fixed top-0 bottom-0 right-0 p-2 w-44 overflow-y-auto
Mano, chapei msm com esse overflow sem necessidade. Vou fazer as correções aq.

2024-09-09 23:13 UTC, SayRyan commented on src/components/sidebar/index.jsx
> +      <div className="fixed right-2 bottom-8">
Como assim, mano?

2024-09-10 00:09 UTC, SayRyan commented
@MatGPereira 

Mano, fiz uns ajustes na estilização, mas não sei um bom lugar para colocar o ícone. Já que vai ser utilizado apenas para mobile, então não faço ideia de um bom local para posicionar. Dei uma melhorada na estilização e dá uma olhada.

2024-09-10 13:26 UTC, MatGPereira commented on src/components/sidebar/index.jsx
> +      <div className="fixed right-2 bottom-8">
Por exemplo: não faz sentido que o botão que abre e fecha a sidebar fique dentro do próprio comoponente da sidebar.
Ou seja, no nosso caso o botão que abre deve ficar dentro do `<header></header>`. Se o sidebar abrir da esquerda para a direita, então o botão que fecha pode tanto estar dentro da sidebar como também pode ser o mesmo botão que abre. 

Se eu não consegui explicar direito, manda mensagem no whats que a gente pega juntos para fazer.

2024-09-11 00:39 UTC, SayRyan commented
@MatGPereira 

Mexi aqui, mas não sei se ficaria bom. Acho que vale a pena pegarmos um dia para mexermos e acabar decidindo certinho essa parada.

2024-09-11 12:23 UTC, MatGPereira commented
@SayRyan, depois a gente pega para fazer juntos.
Como é só para a parte do Mobile, então não é tanta prioridade ainda. Mas aí assim que der a gente faz juntos.
Vocês fizeram a tela de ramos?

2024-09-11 22:30 UTC, SayRyan commented
@MatGPereira 

Blz, mano. A página de Ramos ainda n fizemos, pois vai estar um pouco corrido amanhã também, aí vou ver se começo amanhã à noite.

2024-10-07 17:31 UTC, MatGPereira requested changes

2024-10-07 17:31 UTC, MatGPereira commented on src/components/sidebar/index.jsx
>      document.querySelector('.sidebar').classList.toggle('translate-x-full');
Esta não é a melhor maneira de se trabalhar diretamente com a manipulação do DOM no React.
Dê uma olhada sobre o `useRef`, porque é com ele que você deverá trabalhar para fazer esta manipulação

2024-10-07 17:31 UTC, MatGPereira commented on src/components/sidebar/index.jsx
> +      <button
Esse botão deve existir fora do componente da sidebar.

2024-10-26 13:08 UTC, merged