Criação da página de galeria
Interdisciplinary-Project/Frontend pull request #22
Opened 2024-09-09 18:55 UTC by SayRyan

@MatGPereira 

Nós fizemos a page de galeria, mas está faltando o código do js para aparecer mais imagens e nós não conseguimos fazer esse código pilantra.

1. Criação inicial da página de galeria

2024-09-09 20:14 UTC, MatGPereira requested changes

2024-09-09 20:14 UTC, MatGPereira commented on src/pages/public/gallery/index.jsx
> +    <div className="pt-12 pb-20">
Aqui a tag correta é a `<section></section>`

2024-09-09 20:14 UTC, MatGPereira commented on src/pages/public/gallery/index.jsx
> +        <div className="pt-12 pb-14">
Não precisa desta `<div></div>` aqui. Esses estilos vocês podem colocar diretamente na tag `<SectionTitle />`.

2024-09-10 00:25 UTC, SayRyan commented
@MatGPereira 

Mano, fiz as alterações lá. Aí vamos combinando ao decorrer dessa semana para fazermos a parte do js para ir adicionando as imagens.
Dá uma olhada lá q deixei uma animação simples.

2024-09-10 13:28 UTC, MatGPereira approved these changes

2024-09-10 13:28 UTC, merged