Criação da pagina ramos
Interdisciplinary-Project/Frontend pull request #25
Opened 2024-09-12 17:36 UTC by DanielFBononi

1.Criação da pagina ramos

2024-09-12 19:12 UTC, MatGPereira requested changes

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +    <>
Vai precisar transformar esse `<></>` em uma tag `<section></section>` para que possamos controlar a largura máxima do conteúdo quando a tela for maior do que `1160px`. Não sei se você lembra, mas precisamos colocar algo como `max-w-[1160px]` e outros detalhes como os paddings.

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +          className="w-[278px] h-[225px] rounded-full cursor-pointer object-cover shadow-lg"
Nós temos uma sombra padrão para todos os componentes. Então vai ter que substituir o `shadow-lg` para `shadow-default`, que é a sombra padrão do projeto.

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +          className="w-[278px] h-[225px] rounded-full cursor-pointer object-cover shadow-lg"
.`A imagem em si não precisa ser clicável, ou seja, não precisa do `cursor-pointer`, porque ela vai servir somente de decoração. Inclsuive, vai ter que adicionar um `aria-hidden="true"` na tag `<img></img>`.

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +      <div className="flex py-14 px-48">
Com a correção que eu coloquei a cima, não vai precisar desses paddings aqui. Nós vamos trabalhar nisso através de um `margin-auto`.

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +          <button className="text-social-brand flex py-10 " id="loadMore" type="button">
Não precisa ter o `id="loadMore"` aqui.
Além disso, os atributos dentro da tag precisam estar cada um em uma linha, tipo assim:
```html
<button
  className="..."
  type="button""
></button>
```

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +            id="loadMore"
Não precisa ter o `id="loadMore"` aqui.
E outro detalhe é que, caso nós tivéssemos um `id` e no botão de cima, eles não podem ter o mesmo nome.
A melhor prática no HTML é que todo `id` seja única dentro de uma página HTML.

2024-09-12 19:12 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +          className="w-[309px] h-[246px] rounded-full cursor-pointer object-cover shadow-lg"
Aqui segue a mesma correção que eu comentei na imagem de cima.

2024-09-12 21:23 UTC, DanielFBononi commented
@MatGPereira  fiz os ajustes solicitados.

obs:a  modal alguem tem que dar um telento nela

2024-09-12 22:58 UTC, MatGPereira requested changes

2024-09-12 22:58 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +  const handleModalOpenLobinho = () => {
Mano, isso não é questão de funcionalidade e sim de estética do código. Além de que espaçamentos verticais e horizontais no código entram como requisitos de Clean Code.
Nesse caso, é bom você dar um espaço entre os states e as functions.

2024-09-12 22:58 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +
Aqui também tem um conjuntos de espaços desnecessários, mano. Deixa somente um espaço entre a function e o return.

2024-09-12 22:58 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +          <p className='text-2xl'><p><span className='text-social-brand '>Lobinho:</span></p>
Agora que eu vi aqui. Não tem necessidade de você colocar esse `<p></p>` em volta do `<span></span>`.

Ou seja, assim é desnecessário: 
```html
<p>
  <p>
    <span></span>
  </p>
</p>
```

Assim é o ideal nessa situação:
```html
<p>
  <span></span>
</p>
```

2024-09-12 22:58 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +          <p className=' text-2xl'><p><span className='text-social-brand '>Junior:</span></p>
Aqui é o mesmo comentário que eu fiz a cima.

2024-09-12 22:58 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +        <div className="flex margin-auto pt-44 gap-x-28 mb-20">
Não precisa colocar esse `mb-20` aqui. O ideal é que o próprio container controle os seus espapaçamentos internos.

2024-09-12 22:58 UTC, MatGPereira commented on src/pages/public/ramos/index.jsx
> +    <section>
Como você vai ver em um dos comentários que eu fiz, aqui você colocaria o `pt-12 pb-20` para controlar os espaçamentos internos

2024-09-13 23:43 UTC, SayRyan commented on src/pages/public/ramos/index.jsx
> +          <p className='text-2xl'><p><span className='text-social-brand '>Lobinho:</span></p>
Meu Deus, que nível de porqueira extrema KKKKKKKKKKKKKKKKK
Tô arrumando aq, @MatGPereira :)

2024-09-14 00:00 UTC, SayRyan commented
@MatGPereira 

Fiz os ajustes necessários e melhorei MUITA PORQUEIRA que estava no código.

Mano, tem que ajustar o modal também, pois está parecendo um modal mobile e tá feio que dói.

![image](https://github.com/user-attachments/assets/04debd1e-873b-4b9f-9d37-b9561ebe2ea1)

2024-09-14 15:03 UTC, MatGPereira approved these changes

2024-09-14 15:03 UTC, merged