Criação da pagina de Configurações
Interdisciplinary-Project/Frontend pull request #36
Opened 2024-09-18 18:43 UTC by SayRyan

@MatGPereira 

Os mlks subiram as alterações da página de configurações, mas pelo que eu vi tem umas coisas bem desorganizadas. Dá uma verificada aí e me passa as correções pra eu fazer aqui.

2024-09-18 19:17 UTC, MatGPereira requested changes

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +    return (
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +        <>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +            <div className="h-96">
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                <div className="flex gap-x-6 cursor-pointer mb-64">
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                    <img src={luis} className="h-24 w-24 rounded-full object-cover shadow-default" />
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                    <button className="text-xl">Upload +</button>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                </div>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                <div className="flex justify-end items-center gap-x-5">
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                    <Link className="text-social-red transition duration-500 hover:brightness-50">
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                    </Link>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                    <Button
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                        type="submit"
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                        variant="green"
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                        content="Atualizar"
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                    />
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +                </div>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +            </div>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +        </>
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-image.jsx
> +    );
Precisa arrumar os erros do ESLint para manter a padronização. Subiram o código mal formatado

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/components/main-personal-index.jsx
> +
Precisa remover esse espaço desnecessário

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/index.jsx
> +
Espaço que não deveria estar aqui

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/index.jsx
> +
Daqui para baixo também têm muitos espaços que não deveriam ter;

2024-09-18 19:17 UTC, MatGPereira commented on src/pages/privates/settings/index.jsx
> +                  [
Talvez seja melhor criar uma variável que armazene esse array com os components. Exemplo:

```js
const tabs = [
  <MainPersonalInformations key="1" />,
  <MainPersonalIndex key="2" />,
  <MainPersonalImage key="3"/>
];

function Settings(){
  return (
    <Tabs
      titles={[...]}
      body={tabs}
    />
  );
}
```

2024-09-19 00:45 UTC, SayRyan commented on src/pages/privates/settings/index.jsx
> +                  [
@MatGPereira 

Mano, arrumei a padronização de código aqui e algumas alterações na questão de estilização. Dá uma verificada aí.

2024-09-19 01:19 UTC, MatGPereira approved these changes

2024-09-19 01:19 UTC, merged