Alterações na page de admin / Ajustes de validações
Interdisciplinary-Project/Frontend pull request #39
Opened 2024-09-21 01:43 UTC by SayRyan

1. Criação de cards
2. Criação de tabela
3. Ajustes de validações

2024-09-21 01:48 UTC, SayRyan commented
@MatGPereira 

Dá uma olhada também no controle de Rotas, pois eu fiz uma tag extra de Route Admin pra eu poder enxergar a tela.

2024-09-23 14:03 UTC, MatGPereira requested changes

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +const ITEMS_PER_PAGE = 4;
Tudo isso pode ser colocado em um outro lugar.

Se você manter aqui, então vamos precisar reescrever este mesmo código caso precisemos utilizar em outro lugar da aplicação. Então. dá uma olhada em uma pasta chama `helpers` dentro do código e você pode colocar lá. Coloca um nome bom para o aquivo onde esse código vai ficar.

No caso, você iria colocar em outro arquivo da linha 32 até a linha 43

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +              <div className="grid grid-cols-2 gap-1 w-6 h-6">
Esse aqui deve ser o ícone, se não me engano.
O que você deve fazer é criar um componente a parte para este campo. Ele está se repetindo 3 vezes nesta página e, só de olhar, nós não temos ideia nenhuma do que se trata. Então, cria esse componente na mesma pasta onde está a tela de admin e usa esse componente aqui.

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +            <div className="flex justify-between items-center pb-4">
Essa `div` deve ser um `article` aqui.

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +    <div className="pt-16 pb-12">
Esse aqui deve ser uma `section` e não uma `div`

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +        <section className="flex gap-x-10 pb-14">
Esse cara aqui deve ser uma `div` e não uma `section`.
Além do mais, é interessante que esses card's sejam componentes separados. Faz mais sentido para o nosso contexto

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +                      <button className="text-blue-600 transition duration-500 hover:brightness-50">
Esses `button` precisam de um `type="button"` também.

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +                  <td className="p-3">{maskEmail(user.email)}</td>
Por questões de clean code, é interessante que você não coloque dessa forma `maskEmail(user.email)`
Faz mais sentido criar uma variável (ou eu state) no componente chamado `maskedEmail` e chamar essa variável/state ali dentro

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +                    <span title={user.name}>{truncateName(user.name)}</span>
Aqui é o mesmo sentido do comentário abaixo. Faz mais sentido ter uma variável/state chamado `truncatedName` que contenha o valor truncado do nome.

Mas fiquei com uma dúvida: para que serve esse `truncateName` exatamente? TIpo, eu entendi que ele trunca o nome, mas porque você fez isso?

2024-09-23 14:03 UTC, MatGPereira commented on src/pages/privates/admin/index.jsx
> +                <tr key={index} className={user.status === 'Ativo' ? 'bg-green-50' : 'bg-white'}>
Não se esqueça que os atributos devem ficar cada um em uma linha dentro da `tag`

2024-09-27 12:18 UTC, SayRyan commented on src/pages/privates/admin/index.jsx
> +                    <span title={user.name}>{truncateName(user.name)}</span>
Para limitar o nome

2024-09-27 12:19 UTC, SayRyan commented on src/pages/privates/admin/index.jsx
> +                    <span title={user.name}>{truncateName(user.name)}</span>
uma função que tem a programação dentro dela para limite de nome

2024-09-27 12:21 UTC, SayRyan commented on src/pages/privates/admin/index.jsx
> +                  <td className="p-3">{maskEmail(user.email)}</td>
Como que eu vou fazer sendo que o maskEmail(user.email) está dentro de uma função que contém um parâmetro dentro do HTML?
Se eu jogar ele pra cima, ele não vai pegar o parâmetro de user.

2024-09-27 18:47 UTC, MatGPereira approved these changes

2024-09-27 18:47 UTC, merged