Criação da pagina Details
Interdisciplinary-Project/Frontend pull request #42
Opened 2024-10-03 17:17 UTC by DanielFBononi

Criação da pagina details

@MatGPereira ve ai o que tem que corrigir, quem ira arrumar sera o @SayRyan

2024-10-03 18:43 UTC, MatGPereira requested changes

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +            className="ml-[740px] rounded font-bold text-4 uppercase text-social-white py-[10px]
Não sei como está, mas acho que isso está errado.
Esse `ml-[740px]` não me parece a melhor forma de fazer o botão ficar corretamente espaçado.

Como o container é um flex-container, então imagino que daria para usar o `justify-between` e depois usar alguma outra propriedade para colocar as coisas no início se ainda for necessário.

Mas precisa testar. Com certeza esse `ml-[740px]` bão deveria estar aí

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +            className="pt-12 pb-14 whitespace-nowrap "
Tem um espaço a mais ao final do `className`

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="LOURDES FRANCISCA" />
Tem erros de `Eslint` no seu código, então vai precisar dar uma olhada na formatação. O problema aqui é que você tem linhas com mais de 120 caracteres.

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-10 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="10/11/1980" />
O `type="text"` do input não é o mais adequado se considerar que aqui iremos colocar datas. Dê uma olhada no MDN sobre os types dos inputs e você vai achar um para datas.

E outra coisa, o que é esse `defaultValue`?

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="LOURDES FRANCISCA" />
Aqui também vai ser necessário colocar alguns tipos de validações, como `minLength=""`, `maxLength=""`, `required` e talvez algum outro.

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="MASCULINO" />
Aqui é mais interessante se o você criasse um componente que servisse como um inpput tipo um combobox. Onde só são permitidas algumas opções.

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="(16) 99884-9800" />
Aqui o `type` também não deve ser `text`.

2024-10-03 18:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +              <a className="text-social-red transition duration-500 hover:brightness-50" href="/admin">Voltar</a>
Isso aqui não pode ser uma tag `a`. Aqui precisamos ter o `Link` do `react-router-dom`.

2024-10-04 14:11 UTC, MatGPereira requested changes
Ainda há muitos erros de Linting em muitas partes de código.
Aparentemente todos relacionados a ultrapassagem da quantidade máxima de caracteres por linha

2024-10-04 18:09 UTC, SayRyan commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-10 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="10/11/1980" />
DefaultValue é para manter um valor padrão dentro do input só para termos um dado fictício para preencher o campo e não deixar ele vazio.

2024-10-04 18:13 UTC, SayRyan commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="LOURDES FRANCISCA" />
Então, mas por que seria necessário colocar esse tipo de validação sendo que essa page vai ser só para visualização de dados?
O adm não vai poder modificar nada, apenas o ramo do usuário e o ativar/desativar

2024-10-04 18:13 UTC, SayRyan commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="LOURDES FRANCISCA" />
Até porque vou deixar todos esses inputs desabilitados

2024-10-04 18:15 UTC, SayRyan commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="MASCULINO" />
O que você acha de um?

select
  option option
select

2024-10-04 19:41 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-10 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="10/11/1980" />
Pessoalmente falando, eu acredito que não há nenhuma necessidade de colocar esse atributo nos inputs.
Não vai influenciar em nada.

E eu fiz alguns testes e não vi nenhuma alteração comportamental ao utilizar este atributo. Vi que ele existe, mas que não deve ser usado como foi colocado. Pode retirar ele de todos os inputs que o tiverem.

2024-10-04 19:43 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="LOURDES FRANCISCA" />
Então, nesse caso, como não será possível realizar nenhum tipo de edição na página, então esses campos nem deveriam ser inputs. Faz mais sentido que sejam textos puros mesmo, como se fosse um documento ou algo assim.

Segue um exemplo com dados fictícios do que eu quero dizer

![image](https://github.com/user-attachments/assets/5f45f5fb-7187-4b82-8196-da69e41c136b)

2024-10-04 19:44 UTC, MatGPereira commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="MASCULINO" />
Sim, a ideia é que o componente seja baseado nisso, mas acho que seja válido criar um componente a parte para isso.
Ele será um select de qualquer jeito, mas encapsulado em um outro componente.

2024-10-05 04:35 UTC, SayRyan commented on src/pages/privates/details/index.jsx
> +                  <input type="text" className="mt-1 block w-full px-3 py-2 bg-gray-100 border border-gray-300 rounded-md" defaultValue="LOURDES FRANCISCA" />
Ah, então, mas sendo <p> ou um <input/>, acho que tanto faz, pq de qualquer jeito não daria para modificar. Apenas Ramo e Ativar/Desativar.
Acredito eu que input fica até mais bonitinho de se ver

2024-10-07 17:32 UTC, merged