Criação da page privacy
Interdisciplinary-Project/Frontend pull request #51
Opened 2024-10-14 05:29 UTC by SayRyan

@MatGPereira 

Fiz a criação da página, dá uma avaliada no code aê.

2024-10-14 12:18 UTC, MatGPereira requested changes

2024-10-14 12:18 UTC, MatGPereira commented on src/pages/privates/privacy/index.jsx
> +    <section className="pt-12 pb-20">
Em volta de tudo vai ser necessário colocar um componente chamado `PageTransition` que é responsável por gerar a animação de transição de rotas.

2024-10-14 12:18 UTC, MatGPereira commented on src/pages/privates/privacy/index.jsx
> +    link.download = 'Currículo - Richard R Carvalho';
Isso aqui é só para deixar registrado: vamos precisar criar o PDF com as políticas de privacidade para poder fazer o download aqui

2024-10-14 12:18 UTC, MatGPereira commented on src/pages/privates/privacy/index.jsx
> +              <button
Como aqui nós somente vamos fazer um download diretamente no front-end, faz mais sentido usar diretamente uma tag `<a></a>` ao invés de ter essa mediação com a tag `<button></button>`.

2024-10-14 13:12 UTC, MatGPereira commented on src/pages/privates/privacy/index.jsx
> +    <section className="pt-12 pb-20">
Dentro do `PageTransition` que eu comentei, você vai precisar colocar também a tag `main`. Ou seja, a estrutura ficaria mais ou menos assim:

```html
<PageTransition>
  <main>
    <section></section>
  </main>
</PageTransition>
```

2024-10-15 17:40 UTC, SayRyan commented
@MatGPereira 

Fiz as alterações junto com o botão de pdf funcionando

2024-10-15 20:08 UTC, MatGPereira approved these changes

2024-10-15 20:08 UTC, MatGPereira commented on src/pages/privates/privacy/index.jsx
> +  const downloadPDF = () => {
Mano, não precisava de tudo isso não, dava para resolver em 1 linha. ksskksks
Mas vou subir assim mesmo, não tem problema.
O importante é que está funcionando.

2024-10-15 20:08 UTC, merged