Cabeçalho
Interdisciplinary-Project/Frontend pull request #7
Opened 2024-08-28 17:11 UTC by SayRyan

Fiz o cabeçalho igual ao figma, mas preciso ver se eu errei em alguma estilização ou se eu poderia estilizar de maneira mais fácil e simples para depois deixar mais fácil na hora de fazer a responsividade.

2024-08-28 18:02 UTC, MatGPereira commented on src/components/header/index.jsx
> +                <img
A tag `<img>` não é uma tag de conteúdo, então ela deve ser escrita da seguinte forma:
```html
<img
  className="w-[95px] h-[98px]"
  src="./src/img/logoterrasaudade.svg" 
  alt="Logo do grupo escoteiro terra da saudade">
/>
```

2024-08-28 18:04 UTC, MatGPereira commented on src/components/header/index.jsx
> +                <div className="absolute right-20 py-[28px] max-w-full">
Não é preciso estilizar com `absolute`, o correto (e mais indicado) seria você transformar o componente wrapper em um flex container.

2024-08-28 18:06 UTC, MatGPereira commented on src/components/header/index.jsx
> +                    <div className="flex gap-[16px]">
A tag `div` não é acessível e nem semântica. Para encapsular menus de navegação, a tag correta é `<menu>`. Então, ficaria algo assim:
```html
<menu>
  <li>
    <a></a>
  </li>
</menu>
```

Tanto por questões de acessibilidade quanto por questões de SEO, é sempre indicado utilizar as tag's semânticas nativas do próprio HTML no lugar de tag's estruturais como `div` e `span`.

2024-08-28 18:12 UTC, MatGPereira commented on src/components/header/index.jsx
> +                {/* Links */}
Por questões de Clean Code, é sempre bom evitar qualquer tipo de comentário no código a menos que seja totalmente necessário e explicativo.
Neste caso, com o uso das tag's semânticas, é bom não existir esse tipo de comentário, porque poluem o código

2024-08-28 18:17 UTC, SayRyan commented on src/components/header/index.jsx
> +                <img
Fechou

2024-08-28 18:17 UTC, SayRyan commented on src/components/header/index.jsx
> +                <div className="absolute right-20 py-[28px] max-w-full">
Blz

2024-08-28 18:18 UTC, SayRyan commented on src/components/header/index.jsx
> +                    <div className="flex gap-[16px]">
Blz

2024-08-28 18:18 UTC, SayRyan commented on src/components/header/index.jsx
> +                {/* Links */}
Blz, mano. Vou fazer os ajustes e te mandar para poder avaliar.

2024-08-29 19:53 UTC, SayRyan commented
Fala aí, @MatGPereira.
Mano, fiz as alterações necessárias aqui no código, aí quando puder, só avaliar novamente. Nois!

2024-08-29 20:23 UTC, MatGPereira requested changes

2024-08-29 20:23 UTC, MatGPereira commented on src/components/header/index.jsx
> +                <div className="flex gap-[16px] items-center">
Por questão de semântica, quando você tem um elemento wrapper envolvendo uma tag `<img />` e você tem, em conjunto, um título ou uma descição, você deve utilizar a tag `<figure></figure>` em conjunto com a tag `<caption></caption>`. Ficaria algo mais ou menos assim:

```html
<figure className="...">
  <img
    className="..."
    src="..." 
    alt="..."
   />
   <caption>
     Grupo <strong>Escoteiro</strong> Terra Da Saudade - 05/SP
   </caption>
</figure>
```

Repare que eu também utilizei a tag `<strong></strong>`, porque ela vai trazer a semântica de uma palavra forte, com ênfase (lembrando que esta tag não significa negrito, e sim ênfase).

Outro detalhe que eu reparei agora, neste caso não é necessário o uso do `<br />`, porque você pode controlar a quebra de linha utilizando a própria largura da tag `<caption></caption>` com a classe utilitária `max-w`.

Agora, com relação à acessibilidade, todo atributo `alt` de imagens devem ser descritivos. Ou seja, dizer "Logo do grupo escoteiro terra da saudade" não traz nenhuma informação de como esta logo é formada. A ideia do texto alternativo é fazer com que alguém que navegue na web através de leitores de tela consigam imaginar a aparência de algo através do texto. Como exemplo, um bom texto alternativo para a logo seria: "Árvore preta com vários galhos e folhas espalhadas com um texto escrito o nome do grupo dos escoteiros"

Outro detalhe com a acessibilidade, como o logo também será um link para retornar à Home, então se faz interessante colocarmos um atributo `title` e um atributo `aria-label` na tag `<figure></figure>`, da seguinte foma:

```html
<figure
  title="Voltar à home"
  ariaLabel=""
></figure>
```

2024-08-29 20:23 UTC, MatGPereira commented on src/components/header/index.jsx
> +                            <a
Não se deve colocar atributos `alt` em links, porque eles são naturalmente acessíveis à leitores de tela.
Na realidade, o que você deve colocar, neste caso (lembrando que isso será alterado quando formos utilizar a lib react-router-dom), são os atributos `rel` e `target` da seguinte forma:

```html
<a
  className="..."
  href="#"
  target="_self"
  rel="next noopener noreferrer follow"
></a>
```

2024-08-29 20:27 UTC, SayRyan commented on src/components/header/index.jsx
> +                <div className="flex gap-[16px] items-center">
Blz, mano.

2024-08-29 20:28 UTC, SayRyan commented on src/components/header/index.jsx
> +                            <a
blz

2024-08-29 21:20 UTC, SayRyan commented on src/components/header/index.jsx
> +                            <a
Matheus, fiz as alterações aqui novamente, mano. Verifique, pfv.
@MatGPereira

2024-08-29 21:23 UTC, MatGPereira requested changes

2024-08-29 21:23 UTC, MatGPereira commented on src/components/header/index.jsx
> +                            <a
@SayRyan, dê uma olhada que algumas tag's `<a></a>` ainda têm o atributo `alt`.
O os atributos `target` e `rel` devem ter exatamente os mesmos valores que coloquei no comentário a cima, porque são valores gerais e já pensando tanto em segurança quanto em SEO.

Então todos links, neste caso, devem ter os mesmos valores de `rel` e `target`.

2024-08-29 21:28 UTC, SayRyan commented on src/components/header/index.jsx
> +                            <a
blz

2024-08-29 21:31 UTC, SayRyan commented
Acho que agora foi, Matheus.
@MatGPereira

2024-08-29 21:32 UTC, MatGPereira approved these changes

2024-08-29 21:32 UTC, merged